rounding-mode: "HALF_UP"
rounding-pattern: "#.##"
recipe-level:
  - {level: 1, display-name: "garbage"}
  - {level: 2, display-name: "regular"}
  - {level: 3, display-name: "rare"}
  - {level: 4, display-name: "mythic"}
